# Generated by Django 2.2.1 on 2019-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20190702_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
